OPENAI_API_KEY = "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"

[law_api]
OC_CODE = "poneteer"
