# Streamlit Secrets 설정 파일
# 이 파일은 절대 GitHub에 올리지 마세요!

[api_keys]
# 기관코드 (이메일 @ 앞부분)
oc_code = "your_oc_code_here"

# OpenAI API Key
openai_api_key = "sk-your-openai-api-key-here"

# 추가 설정 (선택사항)
[settings]
# AI 사용 여부 (true/false)
use_ai = true

# API 호출 간격 (초)
api_delay = 0.5
